### ISSUE TITLE
Syntax declarations aren't babeled

### ISSUE THREAD

**Issue by bopjesvla** [mozilla/sweet.js#512]
`let f = (a = 5) => a; [f] = [f]` works.

```syntax s = ctx => { let f = (a = 5) => a; [f] = [f]; return #`` }``` doesn't work.

**Comment by disnet** [comment]
This is fixed in #511.

**Comment by bopjesvla** [comment]
Is it? I might've messed something up, but I switched to the fix-babel branch and the second one-liner still throws.

**Comment by disnet** [comment]
Did you run "npm run dist"? I didn't check in the build.

**Comment by bopjesvla** [comment]
Ah, that's it. I thought I did, but apparently before switching branches.

**Comment by disnet** [comment]
Fixed with #511
